### ISSUE TITLE
Embedding links/actions within a message?

### ISSUE THREAD

**Issue by zackthehuman** [jasonmit/ember-intl#102]
I can't figure out how to get the following scenario working. Consider the following string:

```
You have <a href="/inbox">4 unread messages</a>
```

In order to make this above work I need to embed a `link-to` into the string. Is it possible to preserve the entire phrase for translation _and_ keep the ability to `link-to` something within the message's output?

**Comment by jasonmit** [comment]
You could, but it will require the htmlbars compiler at runtime.  What you're essentially trying to do is build a template out of the output of the format-message helper.

Is that correct, or am I misunderstanding?

**Comment by zackthehuman** [comment]
@jasonmit Yes, essentially I think that's what I want to do. I don't want to compile templates at runtime, but there may not be any other good option if this functionality needs to be supported.

As for splitting up the translation, I'm afraid that just doesn't work in practice. The translator needs to be able to reorder things -- if you split the translation up you're essentially locking words in a specific order (in this case the `You have` will always come before or after the rest of the sentence because you need to place the translation output in _some order_ in the template).

It's hard for me to imagine that this isn't a large-scale problem with internationalization in Ember.

**Comment by stefanpenner** [comment]
> I don't want to compile templates at runtime, but there may not be any other good option if this functionality needs to be supported.

yes don't do this ;)

**Comment by jasonmit** [comment]
You could precompile your translations since they're effectively templates in your case.  I currently do not have the bandwidth to implement this, but I'm opened to reviewing any pull requests.

**Comment by stefanpenner** [comment]
this is a pretty interesting problem. It seems like only a slight misalignment between ember and the underlying intl usage to make this really quite nice.

An example for links, would be to just treat all links that aren't `target="_bank"`  as route transitions. As for actions, some micro-syntax could be used, a predefined event is fired and captured by the intl helper, and then re-dispatched as an ember actions.


Ultimately though, I would be extremely interested in seeing if the intl format could be expressed in pure HTMLBars, and precompiled as part of a translators work-flow.

**Comment by jasonmit** [comment]
I'm skeptical of implementing a special syntax for this.  It seems like it would become maintenance nightmare as I'd surely be touching private APIs to achieve this.

**Comment by zackthehuman** [comment]
The way that we solved this issue for our ember applications is that we have an `anchor` placeholder type, similar to how `plural` or other placeholder types work. We also have a helper that is similar to `link-to` except it generates the link data instead of the link itself. Then we feed the placeholder the value of our `link-to` helper and it does the right thing.

    Go to {:url,anchor,text#the place}!

Then when we use it:

    {{t "some_string_key" url=(t-link-to "someRoute" param1 param2)}}

It's not super clean but it works and it's not too bad.

**Comment by jasonmit** [comment]
@zackthehuman does this t-link-to also some how setup the proper event handlers so that routing still works within your app w/o tearing down the app each time?  Or are these external links?

Did you end up extending intl-messageformat to handle your custom argument type?

**Comment by zackthehuman** [comment]
@jasonmit Yes, I ended up doing something similar to how [ember-href-to](https://github.com/intercom/ember-href-to) works by adding an event handler that talks to the router in an initializer. This is not part of `t-link-to` but works in conjunction with it.

For this project I'm not actually using `intl-messageformat` since we have a standard message format at our company that isn't the same, but it's very similar. I figured that I would share our approach since it's possible that it could work with some modification for `ember-intl`.

**Comment by Turbo87** [comment]
@jasonmit @zackthehuman @stefanpenner has there been any progress on this? it seems like a rather large deal breaker to me unfortunately. how are other companies solving this issue? is https://github.com/intercom/ember-href-to able to solve at least part of this?

**Comment by zackthehuman** [comment]
@Turbo87 not from my side. As I stated in previous comments, we don't use `intl-messageformat` at my work -- we use a custom `messageformat`-like language which we have extended to support constructs like embedded anchors.

I think this is a fundamentally missing aspect of ICU messages in general -- the concept of an abstract hyperlink.

**Comment by vvohra** [comment]
@Turbo87: you said this was a deal breaker for you earlier this year. Did you have any strategies to deal with this problem?

**Comment by Turbo87** [comment]
@vvohra yes, I've tried https://github.com/intercom/ember-href-to and it works very well.

**Comment by jasonmit** [comment]
This works great @Turbo87 - thanks, I'm going to close this for now since there is a solution.
