### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by jasonmit** [jasonmit/ember-intl#285]
- [ ] custom compiler support #350 
- [ ] `translationsFor`, `addTranslation(s)` should be be synchronous
- [x] move configuration off `config/environment` (2.6.0)
- [x] auto inject polyfill by default (https://github.com/yahoo/ember-intl/pull/284)
- [x] validate addon story
  - [x] merge all ember-intl translations into the application translation structure at build time
    - ember-cli exposes an object that has the ability to discover addons, however it's not marked as public and a discussion needs to happen with the coordination of ember-cli to determine whether or not to mark it public

This list is expected to grow.

**Comment by JackieChiles** [comment]
> merge all ember-intl translations into the application translation structure at build time

:+1:

Has there been any movement on this?

It's currently a stumbling block for my team. One workaround we currently have is to use an instance initializer in the addon to add the translations to ember-intl, but they don't sit in the translations directory as JSON, which is a drawback.

It seems like there would be a Broccoli way for addons to work around this for now. What do you think? After a quick look I'm not sure how best to do that without duplicating pretty much all of https://github.com/yahoo/ember-intl/blob/master/packages/ember-intl/index.js

**Comment by jasonmit** [comment]
> One workaround we currently have is to use an instance initializer in the addon to add the translations to ember-intl, but they don't sit in the translations directory as JSON, which is a drawback.

Yeah, that's what I would recommend for now.

The issue preventing me from implementing it is I would be accessing private/undocumented methods of ember-cli to implement it.  I spoke with Robert Jackson a month or two ago about seeing if we can mark them public and he seemed to entertain the idea.  I just need to carve out time to implement it at this point.

**Comment by JackieChiles** [comment]
Ok, no problem, just thought I would ask. Turns out one of our guys just (in the last hour) found a more elegant Broccoli solution to feed translations from addons to ember-intl, so we should be good for now anyways.

**Comment by jasonmit** [comment]
@JackieChiles I had to finish up a few tasks, and now plan to tackle this next.  Glad to hear your team work through the issue and sorry you had to!

**Comment by jasonmit** [comment]
Most of the pieces have landed, custom compiler will also happen soon but can be done without a major version bump so I'm closing this for now.
