### ISSUE TITLE
Build fails with addon/engine

### ISSUE THREAD

**Issue by vlascik** [jasonmit/ember-intl#312]
`The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, symlink 'P:\engine\translations' -> 'p:\app\tmp\funnel-output_path-LSVwGGFX.tmp\__addon__\engine'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at symlinkWindows (p:\app\node_modules\symlink-or-copy\index.js:90:16)
...
`
Problem seems to be in index.js -> included(),
```
     return new Funnel(addon.path, {
        srcDir: addon.translationPath,
        destDir:  path.join('__addon__', addon.name)
      });
```
`__addon__` directory doesn't seem to be created before copying, if I just change it to `destDir:  '__addon__' + addon.name`, build works.

**Comment by jasonmit** [comment]
Engine's have not yet been validated, right now I only support addons.  That said, I haven't experienced this yet.

Can you push an example so I can see what might be happening?  I have an example app and addon running and haven't seen this behavior.

**Comment by jasonmit** [comment]
I'll just prefix with __addon__ instead of creating an __addon__ folder and adjust the sorting to take this change into account.  This should be fine while I investigate the underlying broccoli-funnel issue which might be a Windows things since I haven't come across it.

**Comment by jasonmit** [comment]
Disregard, do not need an example app to reproduce.  This seems to be a bug with broccoli-funnel + Windows.  But I will implement a workaround and version as 2.8.2 shortly.

**Comment by jasonmit** [comment]
Published

**Comment by vlascik** [comment]
That was fast :) Thanks, it works.
