### ISSUE TITLE
Ember CLI build fails due to JSHint running against ember-intl

### ISSUE THREAD

**Issue by JackieChiles** [jasonmit/ember-intl#322]
The `isDevelopingAddon` function is returning `true` always, which means that the Ember CLI build for projects referencing ember-intl will run JSHint (and JSCS) against the ember-intl addon. This can fail the build if the consumer's JSHint rules do not match.

For reference: https://github.com/jasonmit/ember-intl/blob/2.9.1/packages/ember-intl/index.js#L30

**Comment by JackieChiles** [comment]
This is only an issue in versions >= 2.8.0, where `isDevelopingAddon` was first added.

**Comment by jasonmit** [comment]
Thanks for reporting, I will fix and version tonight

**Comment by jasonmit** [comment]
2.9.2 resolves this
