### ISSUE TITLE
How to get translations in objects with no ember container

### ISSUE THREAD

**Issue by ctusch** [jasonmit/ember-intl#323]
Services can only be injected into objects that have a container. I need to access intl.t in an object that doesn't have a container. Importing ember-intl doesn't really work because I only get the class and not the specific service singleton instance that already contains the right locale etc.

Of course there are ugly workarounds like passing the service from some other object that has a container. But this could get extremely ugly and sometimes maybe isn't even possible.

Is there some other way to do this? Am I missing something?

**Comment by jasonmit** [comment]
This is all be design and services can only be injected into Ember Objects.  What you can do is create an instance initializer and expose the service as a global or pass it by reference to the POJO.  Personally, I've never done either.

```js
// app/instance-initializers/global-intl.js
export default {
  name: 'globalify-ember-intl',
  after: 'ember-intl',
  initialize(app) {
    window.intl = app.lookup('service:intl');
  }
}
```
