### ISSUE TITLE
More Polyfill Options for 3.0 (New Feature?)

### ISSUE THREAD

**Issue by justinaray** [jasonmit/ember-intl#324]
I love the work done in https://github.com/jasonmit/ember-intl/pull/284 and think auto-polyfill should definitely be a built-in feature of the add-on.  However, I wanted to make a few suggestions for improvement possibly before a 3.0 timeframe when a breaking change could be introduced.
1. Suggest that an addon user could specify a polyfill type (CDN vs self-served)
2. Suggest that the self-served polyfill could be configured as lazy and dynamically inject the locale script on locale change (I have tested this in Safari and it seems to work fine!)

Here is just a suggestion on what the config variants could be if we stick with the add-on contentFor hooks:

```
intlPolyfill: null // no polyfill needed
intlPolyfill: {
  type: 'cdn|selfServed',
  loadMethod: 'static|dynamic'
}
```

**-or-**

Suggest exporting modules that addon consumers could use in their own `ember-cli-build.js` to do the 3 CDN methods described above (CDN, self-served-static, self-served-lazy) as it seems the `contentFor` hooks are deprecated for add-ons: https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1633

I have provided a lot in here, mostly just for consideration and comment.  Would also be happy to help out if you need.

**Comment by jasonmit** [comment]
A lot to digest, but will respond once I can investigate everything mentioned.  But I agree with more or less everything you've said.  My goal is to make it easier to get up and running w/ little to not interaction around IntlJS + CLDR data.

**Comment by justinaray** [comment]
haha .. yeah, sorry for the epic-ness of the issue.  It's not so much of an issue as a collection of thoughts.  I kept trying to break it up, but it's all intertwined.  In the end, I fully expect this to be multiple issues/PRs (assuming you think it's a good direction) and would be happy to help if you want.

Kudos to basing this impl on IntlJS!  I love following the specs and, with the addition of the auto-polyfill, I think an add-on user could be totally ignorant to the nitty-gritty of IntlJS, etc. ... if they wanted to.

I like to know how the sausage is made, so I have done quite a bit of research to the underlying specs while transitioning my app over to ember-intl.  If you would like to know some of the lessons-learned and gotchas of someone green to IntlJS and ember-intl, have a look at my [notes](https://github.com/justinaray/tech-notes/blob/master/web/intl-emberIntl.md).  Might provide some base info you could add to the README.

**Comment by jasonmit** [comment]
> I fully expect this to be multiple issues/PRs (assuming you think it's a good direction) and would be happy to help if you want.

I would love the help to get started on your proposed 1 and once it's solidified we can move on to number 2, dynamically loading locale data or embed them statically.

I did some quick research and it seems `contentFor` isn't deprecated the contentFor hooks for `app-prefix` and `app-suffix` are -- so we can continue it to push content into the head.

> I like to know how the sausage is made, so I have done quite a bit of research to the underlying specs while transitioning my app over to ember-intl. If you would like to know some of the lessons-learned and gotchas of someone green to IntlJS and ember-intl, have a look at my notes. Might provide some base info you could add to the README.

This is great, I've always wondered what the experience was like on-boarding.  I've just opened up the wiki section so feel free to append what feel is missing.  I'm sure it will be incredibly valuable coming from a fresh view of the landscape.

**Comment by jasonmit** [comment]
First part of this has been merged, the autoPolyfill for index.html.  We can now do the second part, being able to decide between served up locally vs CDN.

**Comment by jasonmit** [comment]
Closing for now, @alexlafroscia wrote a great polyfill.io ember-cli addon that might be better suited now.
