### ISSUE TITLE
ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by sajt** [jasonmit/ember-intl#329]
In `ember-intl/addon/formatters/format-number.js` in line 18. I only get this error in Safari (OSX Version 9.1 (11601.5.17.1)).

If I do not use formatNumber there is no error. In other browsers (Firefox, Chrome where i tried) there is no erreor

**Comment by jasonmit** [comment]
You're not loading the polyfill, look at https://github.com/jasonmit/ember-intl/wiki/Intl.js-Polyfill

Safari is one of those browsers you need to polyfill the Intl API
