### ISSUE TITLE
services:intl locales leaking into user-space options

### ISSUE THREAD

**Issue by justinaray** [jasonmit/ember-intl#332]
If your options object happens to be persistent across calls to `t`, then you can run into a situation where the current locale(s) leak out into that instance and override the default locale stored in the service

```javascipt
let recipient = {who: 'World'};
intl.setLocale('en-us');
intl.t('say.hello', recipient); // 'Hello World'

// At this point, recipient contains a locale property and will override the default in the service

intl.setLocale('es');
intl.t('say.hello', recipient); // 'Hello World' ... expected 'Hola World'
```

# Possible Bug Location

In `services:intl`, the function returned by `formatterProxy` appears to directly update the provided `options` value with the service's `_locale`.  I think the bug might be [in the extend call](https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/addon/services/intl.js#L25).  Not exactly sure how the custom `extend` util works, but if it's like other libraries, an empty seed object could be used to clone the provided object rather than directly manipulating it.

**Comment by jasonmit** [comment]
Good catch and thanks, I'll write a failing test in a bit

**Comment by justinaray** [comment]
np!

Was going to write a twiddle or fork the repo, but figured you could reproduce much quicker than I could 😄 

I just realized that it doesn't really require a persistent object.  Just changing the locale will do it as the call closes upon the object.

Thanks for the quick filing and response as usual @jasonmit!

**Comment by jasonmit** [comment]
Test added and will work on a fix tonight

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-intl/pull/333/files fixes the issue, just want to look at it closer tonight before versioning

**Comment by justinaray** [comment]
🙌  impressive @jasonmit!  I was going to add one more case but you implemented it before I could even PR a breaking test case!

The other thing I noticed is that you cannot provide a null value as options.  Likely due to es2016 only recognizing default values for `undefined` as opposed to `null`.

Didn't know how you felt about making `t` null safe for options.  I came across this accessing `t` programmatically in a component where I may or may not have replacements.

Can open another issue if you want to go ahead and push `333`.

Thanks again!

**Comment by jasonmit** [comment]
> Didn't know how you felt about making t null safe for options

Can you open another issue for this and explain with maybe an example snippet.  I'll try and fix this along with another smaller issue I discovered while fixing this before versioning.

**Comment by justinaray** [comment]
Awesome!!!  Thanks!

Null-safe Issue: https://github.com/jasonmit/ember-intl/issues/334

**Comment by jasonmit** [comment]
2.10.0 contains this
