### ISSUE TITLE
Make t and formatX calls null safe for options

### ISSUE THREAD

**Issue by justinaray** [jasonmit/ember-intl#334]
Currently, `formatterProxy` is `undefined` safe but not `null` safe for options.  If you pass null, a TypeError is thrown.  This is because the es2015 default value only supports undefined, not null.

https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/addon/services/intl.js#L20

# Use Case

In my use case, this occurs in a msg-display component where I may or may not have replacements.

```
msgKey: null,
msgReplacements: null,

...
  this.get('intl').t(this.get(`msgKey`), this.get('msgReplacements')); // throws a TypeError
```

Granted, this is easy to defeat in the call, but it seems null could safely be considered as empty in this context.

**Comment by jasonmit** [comment]
2.10.0 contains this
