### ISSUE TITLE
error in 2.10.0

### ISSUE THREAD

**Issue by duboff** [jasonmit/ember-intl#340]
```
Unexpected token ']'. Expected ')' to end a argument list.
```
Hi, we updated from 2.6.1 to 2.10.0 and see this error in production (works fine in development and test). Can't track down the error more precisely as of now. I might have missed something glaringly obvious in the docs. Would appreciate any guidance.

**Comment by jasonmit** [comment]
Can you post the full stack trace

**Comment by jasonmit** [comment]
If i were to guess, it's due to Ember.warn/Ember.deprecate which noop in production-mode but in this case something is happening there.  I'll know for sure once I see the stacktrace

**Comment by duboff** [comment]
Can't really produce the stack trace since it's production and I can't reproduce locally for now.

**Comment by jasonmit** [comment]
Just pretty pretty it with a screenshot and I think I'll get a sense of what is happening.

![screen shot 2016-04-25 at 2 34 19 pm](https://cloud.githubusercontent.com/assets/3108309/14799724/ed3a175e-0af2-11e6-8261-4529b33fa687.png)

{} in the bottom left hand corner

**Comment by duboff** [comment]
I had to revert unfortunately as this stopped app from working. Will try to recereate in a safe environment and paster here

**Comment by duboff** [comment]
Apologies, after more testing it seems the error comes from moment.js, not this addon.

**Comment by jasonmit** [comment]
Thanks for reporting back.  Was this an issue in ember-moment or moment.js?  I help maintain ember-moment as well.

**Comment by duboff** [comment]
Not sure. Rolling moment itself to 2.10.6 fixes the problem but given how widely it's used and lack of issues there I assume it's some combination of things. I sent you a link on slack to the page with error if you want to do some digging.
