### ISSUE TITLE
Programmatic invocation of `t` always produces a warning (And deprecation)

### ISSUE THREAD

**Issue by justinaray** [jasonmit/ember-intl#341]
I think this might be a slight regression due to [#337](https://github.com/jasonmit/ember-intl/pull/337) ... sorry :(

Previously, I could invoke `t` with no options or formats and it would use the current values stored in the `intl` service.

```
this.get('intl').t('myKey'); // now throws a warning
```

Additionally, the warning throws an Ember deprecation as it is lacking an options hash with an id property.  http://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options

Ember: 2.4.5
Ember-cli: 2.4.3
ember-intl: 2.10.0

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-intl/pull/342 will fix this

**Comment by jasonmit** [comment]
Versioned, thanks again

**Comment by justinaray** [comment]
👍

Will pull `2.10.1` today and confirm.

All the gratitude belongs to you @jasonmit.  Thanks for the quick fix.

**Comment by justinaray** [comment]
Confirmed:
* The warning is no longer thrown on `services:intl.t('myKey')` on `2.10.1`.
* If undefined or null are explicitly passed the warning is thrown while in develop mode but not in prod :sparkles:

I did notice that Ember is still throwing a deprecation warning on the `Ember.warn` call due to missing an options hash.  But this is deprecated through Ember 3 so there's no rush.

Thanks again for the fix!

**Comment by jasonmit** [comment]
I'll fix that as part of 2.11.0

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-intl/commit/685d26ecdd49afd119d9783f88c65589e6fe6c33 will fix the deprecation warnings

**Comment by justinaray** [comment]
`685d26e` looks great.  Thanks!
