### ISSUE TITLE
Polyfill locales not getting copied to output folder

### ISSUE THREAD

**Issue by ctusch** [jasonmit/ember-intl#344]
Hey,

we're using ember-intl 2.6.1. When we started using it all locales where copied to assets/intl/locales/. We changed `locales` to only include `en-us` and `de-de`. Back then this worked as well. But somewhere along the way something broke.

Now not even then ´locales´ folder is created during build. Deleting my output and my `tmp` folder does not help. The `intl` folder with its libs is there as usual. When I manually copy the locale files from `node_modules/intl/locale-data/jsonp` everything works as expected.

Here is the content of `config/ember-intl.js`:
```JavaScript
/*jshint node:true*/

module.exports = function(environment) {
  return {
    locales: ['en-us, de-de'],
    baseLocale: 'en-us',
    disablePolyfill: false,
    publicOnly: false,
    inputPath: 'translations',
    outputPath: 'translations'
  };
};
```

The build process doesn't give me any errors.

**Comment by jasonmit** [comment]
Can you verify this goes away with 2.10.x?

**Comment by ctusch** [comment]
Hey, sorry for the late feedback. 2.10.1 fixed this! Curiously it also logged the following warning during build:

    [ember-intl] 'en-us, de-de' is not a valid locale name

Turns out I forgot the string delimiters in my ember-intl.js from above. Totally missed that. After correcting it it also worked again in 2.6.1.

Sorry for the inconvenience!

**Comment by jasonmit** [comment]
Thanks for reporting back and no issue, glad I threw those warnings in :)
