### ISSUE TITLE
Investigate precompiling

### ISSUE THREAD

**Issue by jasonmit** [jasonmit/ember-intl#349]
See the amount of work is needed to implement precompiling for intl-messageformat or to adopt messageformat.js (would require a fork to support everything intl-messageformat supports today)

**Comment by GCheung55** [comment]
@jasonmit this is closed so what was the outcome?

**Comment by jasonmit** [comment]
Unsupported.  Changes required upstream for this and I plan to make this possible.  Happy to revisit in the future.
