### ISSUE TITLE
NumberFormat().format(null) and Intl.DateTimeFormat().format(null) return Empty String

### ISSUE THREAD

**Issue by ajgordo** [jasonmit/ember-intl#351]
We have a project where we need null to be treated as an empty string rather than formatted as 0 or Epoch time. I see other issues on using "allowEmpty: true", but this seemed to do nothing for me.

Is the only answer to create my own helper the encompasses these to return an empty string in the case of null, or is there something already there and I'm just overlooking it?

**Comment by jasonmit** [comment]
Do you need this for the helpers and/or computed property macros?  Debating adding a beforeFormat hook that would be optional and would pass the value and formatterType as args.

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-intl/commit/d7b1927ac74819aa0d2d2b56f5bdcde359f990a5

I wasn't able to reproduce this, it is returning an empty string as expected and not 0.

**Comment by ajgordo** [comment]
Is there a property of the intl service that I can confirm is set/not set to ensure it does return an empty string? I see that its the default behaviour, but that isn't what we see (and we are on 2.11.1)?

**Comment by jasonmit** [comment]
> Is there a property of the intl service

This is a per-helper thing, not globally handled by the service or config.  Though, I'm not against supporting that - it just hasn't come up yet.

> I see that its the default behaviour,

For Number it is not defaulting to allowEmpty.

**Comment by ajgordo** [comment]
It seems you are referring to the handlebars helpers, whereas I'm referring to the service which doesn't seem to support it natively? Neither intl.DateTimeFormat().format() or intl.formatDateTime see to handle the use of nulls (yes, I need to do this in code and not a template). 
Sorry, should have clarified.

**Comment by jasonmit** [comment]
`Intl.DateTimeFormat` and `Intl.NumberFormat` are not a product of ember-intl but instead part of either the native browser API or the polyfill for the API.  I wouldn't recommend hijacking those lower level APIs to handle passing null but instead would reimplement the service methods you're calling (`intlService.formatNumber`, `intlService.formatDate`, `intlService.formatTime`)

That shouldn't be too difficult to reopen the service to implement an escape value before calling super on those methods.  That would look something like the following:

```js
// app/services/ember-intl

import Service from 'ember-intl/services/ember-intl';

export default Service.extend({
  formatDate(value) {
    if (value === null) { return ''; }
    
    return this._super(...arguments);
  },
  formatNumber(value) {
    if (value === null) { return ''; }
    
    return this._super(...arguments);
  }
});
```

**Comment by jasonmit** [comment]
@ajgordo feel free to reopen if you need further help
