### ISSUE TITLE
Intl config not being read

### ISSUE THREAD

**Issue by vlascik** [jasonmit/ember-intl#352]
At least on Windows (haven't tested elsewhere), in `readConfig` function in `index.js` the config path is wrong
```
var configPath = path.join(project.root, project.configPath(), '..', 'ember-intl.js');
```
leads to paths like `C:\Project\C:\Project\config\environment\..\ember-intl.js`, as `project.configPath()` returns the full path (in 2.6.0). Intl config file is then not found and read.
Changing the line to
```
var configPath = path.join(project.configPath(), '..', 'ember-intl.js');
```
fixes the problem.

ember-intl: 2.11.1
ember: 2.6.0.beta.4
ember-cli: 2.6.0-beta.3
node: 6.2.1
os: win32 x64

**Comment by jasonmit** [comment]
Thanks, I'll look to patch today/tonight.

**Comment by jasonmit** [comment]
Versioned as 2.11.2, please reopen if the issue continues.

**Comment by vlascik** [comment]
Hm, doesn't work, probably because regexp needs double backslashes. This works for me in Windows:
```
var configPath = path.join(project.configPath().replace(new RegExp('^' + project.root.replace(/\\/g, '\\\\')), ''), '..');
```

**Comment by jasonmit** [comment]
I'll keep 2.11.2 published since it fixes it for POSIX users, I'll need to figure out a way to spin up a VM for windows.

**Comment by vlascik** [comment]
There should be free VMs here:
[https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/)
Haven't tried it, but these should be valid for 90 days, if you create a VM snapshot after the install you can revert to it after the VM expires.
