### ISSUE TITLE
How would ICU compiling at run time work?

### ISSUE THREAD

**Issue by mellatone** [jasonmit/ember-intl#354]
Trying to use this with computed properties:

```js
dynamicMessage: computed('amount', function(){
  let amount = this.get('amount');
  return this.get('intl').formatMessage('something.yaml.path', `{ amount: ${amount } }` );
})
```

**Comment by jasonmit** [comment]
The syntax is wrong, you have the template string ticks in the wrong spot.  Otherwise, there is nothing wrong with what you have.

```js
dynamicMessage: computed('amount', function(){
  let amount = this.get('amount');
  return this.get('intl').formatMessage('something.yaml.path', { amount: `${amount}` });
})
```

**Comment by jasonmit** [comment]
Correction: you want to use this.get('intl').t('something.yaml.path', { amount:${amount}});

formatMessage is used when you want to pass a translation string. t is used when you want to translate a translation key.

**Comment by mellatone** [comment]
Ah, great. Thank you. this is what I needed.

I was confused by the readme:
> A short-hand form of the {{format-message}} is {{t}}.
