### ISSUE TITLE
README - should config file location be updated?

### ISSUE THREAD

**Issue by menewman** [jasonmit/ember-intl#356]
The README has a Translation Compilation section that describes how to set the base locale. It also includes this snippet:

```
// config/environment.js
return {
  intl: {
    baseLocale: 'en-us' // default build-time locale
  }
};
```

But if you put this code in config/environment.js, you'll see a warning advising that config/ember-intl.js is now preferred over config/environment.js for ember-intl configuration. Should this be updated to specify that the `baseLocale` property should be set in config/ember-intl.js now? (I'd be happy to submit a PR if I'm not off-base here.)

**Comment by jasonmit** [comment]
Yes, the README should be updated to reflect this change.

> I'd be happy to submit a PR if I'm not off-base here

Pull requests are always welcome :)
