### ISSUE TITLE
different configs per environment?

### ISSUE THREAD

**Issue by adhamhf** [jasonmit/ember-intl#358]
Hi,

I would like to have different a different configuration for development and test than I do for production.  I would like use the translations directory when in dev/test and load from an AJAX call when in production.

I'm not sure how to do this with the deprecation of environment.intl.

Suggestions?

**Comment by jasonmit** [comment]
The config takes the environment as an argument:
https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/config/ember-intl.js#L3

`environment` should be `test`, `development`, or `production`.  So you can put a switch or if statements to construct what the config looks like in those environments.

**Comment by jasonmit** [comment]
Feel free to open if this doesn't answer your question.

**Comment by donahchoo** [comment]
@jasonmit I do need to reopen this...  I have this code:

```
module.exports = function( env ) {
    console.log('ember-intl env', env);
```

but when I do ```ember serve``` I get this output:

```ember-intl env undefined```

am I doing something wrong?

**Comment by adhamhf** [comment]
@jasonmit I do need to reopen this... I have this code:

module.exports = function( env ) {
    console.log('ember-intl env', env);
but when I do ember serve I get this output:

ember-intl env undefined

am I doing something wrong?

**Comment by jasonmit** [comment]
@adhamhf you're correct.  I've patched it and will version shortly.

**Comment by jasonmit** [comment]
2.13.0
