### ISSUE TITLE
Safari - `Intl is not defined` error causes apllication to abort startup

### ISSUE THREAD

**Issue by kashiif** [jasonmit/ember-intl#359]
[The instance-initilizer module checks for `Intl` variable](https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/app/instance-initializers/ember-intl.js#L29). Only in Safari, this results in following error during application startup causing it to fail

    ReferenceError: Can't find variable: Intl
        didBecomeReadyember.debug.js:4874
        invokeember.debug.js:332
        flushember.debug.js:396
        flushember.debug.js:204
        endember.debug.js:559
        ...

Weird that the same project works in Firefox and Chrome without complaining about Intl not being there. Fixing this would atleast let the application run without il8n support when Intl is not present.

**Comment by jasonmit** [comment]
> Weird that the same project works in Firefox and Chrome without complaining about Intl not being there. Fixing this would atleast let the application run without il8n support when Intl is not present.

Safari is one of the browser that doesn't natively implement the Intl API.

https://github.com/jasonmit/ember-intl/wiki/Intl.js-Polyfill
