### ISSUE TITLE
0 not being displayed

### ISSUE THREAD

**Issue by hvgotcodes** [jasonmit/ember-intl#362]
In my template

`{{t "key" count=0}}`

in en-US.json

`"key": "{count} things"`

does not show "0 things" in the dom.  if I change count to 1 it works.

On a related topic, is there support for different "conjugations", like

0 things
1 thing
10 things

**Comment by jasonmit** [comment]
> Use {num, number} instead.

Related to https://github.com/yahoo/intl-messageformat/pull/136
