### ISSUE TITLE
Version 2.12.0 is unstable.

### ISSUE THREAD

**Issue by kashiif** [jasonmit/ember-intl#363]
The module [lib/unique](https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/lib/utils/unique.js) still uses the lodash that was [removed](https://github.com/jasonmit/ember-intl/commit/54c9f25a819bd7e2cfaa6bff2a27b856fee2e876#diff-3979d4d267fedd64b8925a7391f8b779L76) from package.json (and replaced by ember-cli-lodash-subset) a couple of days ago.

**Comment by jasonmit** [comment]
2.12.1 resolves this
