### ISSUE TITLE
hour='2-digit' doesn't work with hour12=false

### ISSUE THREAD

**Issue by georgi-kovachev** [jasonmit/ember-intl#366]
{{format-date notification.created_at hour="2-digit" minute="2-digit" hour12=true}}
I used hour='2-digit' and hour12=true but it still shows one-digit hour.
11:18 pm -- fine
9:43 pm -- 
3:10 pm 
3:02 am

And I use 2.2.1 in package.json
"ember-intl": "2.2.1",

**Comment by jasonmit** [comment]
@georgi-kovachev is this with or without the IntlJS polyfill?  If with, what version of the polyfill and what browser?

**Comment by georgi-kovachev** [comment]
I don't think it uses polyfill, and I think it is my misunderstanding about time format.
I thought it should be displayed like this 09:23 pm but generally leading-zero hour will be available in 24-hour format.
Now I am confused whether it is a bug or not about '9:23 pm' with this parameter .
 hour="2-digit" minute="2-digit" hour12=true

**Comment by jasonmit** [comment]
> I don't think it uses polyfill

Which browser are you using when you see this?

**Comment by jasonmit** [comment]
This doesn't appear to be a bug within ember-intl.

```js
new Intl.DateTimeFormat('en-US', {
  hour: '2-digit',
  minute: 'numeric',
  hour12: true
}).format(new Date('2000/12/12 13:09'));
// => "1:09 PM"
```

This is how Chrome has implemented the DateTimeFormat API.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat
