### ISSUE TITLE
Refer already defined translation

### ISSUE THREAD

**Issue by pbosse** [jasonmit/ember-intl#371]
Hi,

Is it possible to refer to an already defined translation? for example:

```
user: 'User'
group: 'Group'
creationOf: 'Creation of'
createUser: '{CreationOf} {user}'
deleteGroup: 'Deletion {group}'
```

Thanks,
Philippe

**Comment by jasonmit** [comment]
This is currently not possible.

**Comment by jasonmit** [comment]
Closing for now, feel free to reopen if you, or anyone in the future, wants to add this functionality.  Would be happy to accept it.
