### ISSUE TITLE
Corrections for autoPolyfill and outputPaths

### ISSUE THREAD

**Issue by nightire** [jasonmit/ember-intl#374]
I found some inconsistent information in documentation, according to https://github.com/jasonmit/ember-intl/wiki/Intl.js-Polyfill#change-output-path, users should be able to specify the output path, but:

1. ~~This is not true if `autoPolyfill` is false. I believe this is a bug, because users may want to change output path event turn off `autoPolyfill` option (`false` is default value, it confuses the beginners).~~ **This is OK actually as long as point 2 is correctly specified**

2. Documentation says we should specify outputPath from `{ outputPaths: { intl: '...' } }`, but [here](https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/index.js#L65) suggests to find the path in `{ app: { intl: '...'} }`. I believe documentation is right this time, since `outputPaths` is the convention that everyone follows to change the assets output name or path.

I can submit PRs if necessary, but I'm not sure whether to fix the documentation or the source code, any suggestions?

**Comment by jasonmit** [comment]
> I can submit PRs if it necessary, but I'm not sure whether to fix the documentation or the source code, any suggestions?

Please do, and I agree on both points.  `autoPolyfill` should respect the output path provided and the README should be updated to reflect `app: { intl: '...'}` instead of `outputPaths: { intl: '...' }`

**Comment by nightire** [comment]
@jasonmit I've changed the wiki now, `autoPolyfill` is fine, I've mis-leaded by the 2nd point. Thanks.
