### ISSUE TITLE
[ember-intl] (...) missing from en-us

### ISSUE THREAD

**Issue by HenryVonfire** [jasonmit/ember-intl#375]
Recently I've updated ember-intl to its latest version and now, when running the project with `ember s`, I'm getting a lot of `[ember-intl] (...) missing from en-us`. My translation file is called `en-US` and I've checked that the correct name (with US in upper case) is set in the `intl.locale` in the  `beforeModel` application route, `baseLocale ` and `locales` in `config/ember-intl` file. Am I missing something?

I've also noticed that all the keys that it says that are missed are from subdirectories. The ones from the root file doesn't appear in the list of "missing". And to make it more strange, although it says that they are missed, all of them are working correctly in the application.

**Comment by jasonmit** [comment]
@HenryVonfire any chance you can throw together a sample app that reproduces this?

**Comment by HenryVonfire** [comment]
@jasonmit Sure, [here](https://github.com/HenryVonfire/intl-log) you have. While doing this I've discovered that it wasn't actually `ember-intl` the one generating the problem but `ember-intl-cp-valdiations`, should I open an issue in that repository?

**Comment by jasonmit** [comment]
Yes please

**Comment by HenryVonfire** [comment]
Ok. I'll close this issue then.

**Comment by jasonmit** [comment]
Should be fixed in ember-intl-cp-validations v2.3.1

Thanks
