### ISSUE TITLE
Fallback language

### ISSUE THREAD

**Issue by martin-hoger** [jasonmit/ember-intl#376]
First of all, thank you for the addon. It is pleasure to use it, I also very much appreciate the intergation with CP Validations.

I have an app with many languages, sometimes it happens that some translated strings are missing, in this case I want "fall back" to English. This is the way I do that:

utils/intl/missing-message.js

```
import Ember from 'ember';

const { Logger:logger } = Ember;

export default function missingMessage(key, locales) {
  // If EN translation is missing finish here and log it.
  if (locales[0] === "en" ) {
    logger.warn(`translation: '${key}' on locale: '${locales.join(', ')}' was not found.`);
    return `Missing translation: ${key}`;
  }
  
  // For other languages then EN we try to load EN translation.
  let intl        = this.container.lookup("service:intl");
  let translation = intl.findTranslationByKey(key, ["en"]);

  return translation;
}
```

I am just wandering, are there some other (better) ways to do that?
It is a good practice to use this.container.lookup("service:intl")?

**Comment by jasonmit** [comment]
`intlService.setLocale(['fr-ca', 'en-us']);` in this case will try fr-ca and fallback to en-us.  Let me know if you experience any issues with this.

**Comment by martin-hoger** [comment]
It works. That's much better. Thank you!
