### ISSUE TITLE
Access current locale when resolving templates

### ISSUE THREAD

**Issue by rewritten** [jasonmit/ember-intl#395]
I am not sure whether it should be a concern of this library, but at some point it make sense to me to have entire templates translated, with rules like in rails, so a `{{partial "my-thing"}}` will be resolved (assuming locale is `en-us`) to the first available of
* `-my-thing-en-us.hbs`
* `-my-thing-en.hbs`
* and finally the non-localized `-my-thing.hbs`.

This is very similar to what rails does with templates.

Of course it is not possible to inject `'intl'` in the resolver (as it is outside of the container), and I have found no pointer to solve this, it seems that it is a non-issue for many.

Would you think that it would be possible to have a Resolver mixin, searching for the templates with the suffix, like
```es6
// intl-template-resolver.js
export default Ember.Mixin.create({
  getTemplateSuffixes() {
    // some magic here?
  },

  resolveTemplate: function(parsedName) {
    let suffixes = this.getTemplateSuffixes();

    while (suffixes.length) {
      let suffix = suffixes.pop();
      let found = this._super(`${parsedName}-${suffix}`);
      if (found) {
        return found
      }
    }

    return this._super(parsedName);
  }
});
```

**Comment by jasonmit** [comment]
How I've dealt with this in the past, at the component level, is make `layout` a computed property.

```js
// components/x-foo/component.js
layout: computed('i18n.locale', function() {
  const locale = get(this, 'i18n.locale');

  return getOwner(this).lookup(`template:components/x-foo/layouts/${locale}`);
})
```

It might make sense to create an addon for this that is agnostic to both ember-intl/ember-i18n.  That said, I'm not against using the resolver for this, I just haven't ventured down that far in my previous attempt to get this working in a project.

**Comment by rewritten** [comment]
If you have any idea of how to get the magic in the resolver, I would be very happy to make the implementation.

**Comment by jasonmit** [comment]
@stefanpenner any suggestions?
