### ISSUE TITLE
Not escape string if it's htmlSafe

### ISSUE THREAD

**Issue by vvohra** [jasonmit/ember-intl#399]
If the prop value is marked as HTML safe, would it make sense to skip the escape done [here](https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/addon/formatters/format-html-message.js#L16)?

**Comment by jasonmit** [comment]
Where the argument you are passing in is htmlSafe?

**Comment by vvohra** [comment]
> If it's an htmlSafe string it should skip that typeof value === 'string'.

You're right, I should have checked. Thanks.

> {{format-html-message 'greeting' name=(html-safe model.firstName)}} something like this is what you're after? If so, I'm on board with officially supporting it.

That already works, I think. So we're good there.
