### ISSUE TITLE
Custom translation directory

### ISSUE THREAD

**Issue by estshy** [jasonmit/ember-intl#400]
I would like to keep translations in different directory than `translations`. I thought about changing `inputPath` and `outputPath` to something different. Unfortunately it doesn't work, because the default path is hardcoded in `node_modules/ember-intl/app/instance-initializers/ember-intl.js`

**Comment by jasonmit** [comment]
@estshy Right now, this isn't supported but in the future I will likely change that if you want to wait.  Otherwise, I'd welcome a PR if you are interested in tackling this.

**Comment by Turbo87** [comment]
IMHO changing the folder would be against the convention over configuration concept in Ember. What reason do you have for changing that folder?

**Comment by jasonmit** [comment]
@Turbo87 we can support both w/o much work IMO.  As someone who frequently bumps up against conventions, having an escape option is always nice.  But it would be nice to know the use-case, perhaps we've overlooked something.

**Comment by Turbo87** [comment]
> But it would be nice to know the use-case, perhaps we've overlooked something.

that's all I'm saying. if there are good reasons to put them elsewhere we can support it, but I'm against supporting stuff just because we can if it increases complexity without much to gain.

**Comment by estshy** [comment]
Well. I would like to keep default language labels locally in the repository and fetch all remaining languages from the api with one little remark. In addition to that I would like to have them inside pods directory.

Why? Navigating through large directory trees sucks a lot. Also I don't want to have translations that are not used anymore, so when I am removing something from the pods directory I want to remove all related translation as well. 

Default folder simply doesn't work well in large scale applications.

**Comment by jasonmit** [comment]
> Well. I would like to keep default language labels locally in the repository and fetch all remaining languages from the api with one little remark.

This is already possible today https://github.com/jasonmit/ember-intl/blob/master/docs/asynchronously-loading-translations.md

As for pods, I would treat that entirely separately than a configurable outputPath.  Perhaps you want to open a separate issue (for tracking) for this.

I have plans to work on an addon that is library-agnostic that will work with ember-i18n and ember-intl to flatten yaml/json translation files.  This way you can put translations anywhere within your app which will address pods.  It likely will not deal with auto-namespacing, but will error/warn on key collisions.

/cc @alexlafroscia who has also expressed interest in this

**Comment by Turbo87** [comment]
@jasonmit that should probably target the new module unification RFC since pods are somewhat deprecated now

**Comment by jasonmit** [comment]
@Turbo87 what I had in mind wasn't targeting any specific app directory shape.  It would glob for `**/*.(yaml,json)` filter on everything that looks like a locale, merge by locale, and remove them from the app tree as they're merged together.

Lets chat over at #401

**Comment by travisghansen** [comment]
For what it's worth, our use case is such that we have an independent repo with the translations that's used for multiple projects (ember and non-ember).  Without the ability to specify the location this becomes cumbersome to integrate :(

**Comment by jasonmit** [comment]
@travisghansen were you planning to use submodules?  Curious the strategy so that I can support it.

**Comment by travisghansen** [comment]
@jasonmit well, our intent was to make a very 'dumb' repo with just the translations and include bare minimum per-language/toolkit packaging 'stuff'.  My hope was to add a simple `package.json` so we could version the translations and just include the npm package from the various js/ember projects.

Outside of npm (ie: `package.json`) we currently have a php app as well so we're dropping a `composer.json` in the translations repo and then simply include the composer package from the various php projects as needed as well.

High-level: `translation repo` -> `ci` -> `when tagged build npm/etc/etc packages` -> `include in various packaging tools as a completely independent package`

**Comment by travisghansen** [comment]
I should note for development purposes it would be ideal to point at any arbitrary folder outside the project structure.

**Comment by jasonmit** [comment]
Thanks for the info, I think I can get this working fairly easy.  I'll ping you once I have something.

**Comment by travisghansen** [comment]
@jasonmit thanks for the consideration!

**Comment by travisghansen** [comment]
Does the existing project have the ability to configure file naming conventions?  ie: en-us.json vs en_US.json etc?

**Comment by jasonmit** [comment]
@travisghansen it looks like I already added support for changing the inputPath but never made it part of the public API: https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/tests/dummy/config/ember-intl.js#L63-L66

Can you verify this works for changing the translation path?  I'll look to make it public and update the documentation.

> Does the existing project have the ability to configure file naming conventions? ie: en-us.json vs en_US.json etc?

Not yet, but something I can implement.

**Comment by jasonmit** [comment]
Okay, everything is on master right now.  The case insensitive translation file names along with the inputPath property made public.

https://github.com/jasonmit/ember-intl/commit/3935bf6b41d0538f1f8b43320a53c50f87d081b1

I plan to version tonight.

**Comment by travisghansen** [comment]
@jasonmit just to be clear, it's also `_` instead of `-` so case insensitive alone won't do the trick on the convention side of things.

**Comment by jasonmit** [comment]
@travisghansen correct.  Your translation files can be named `en_US.json` or `en-us.json` or `en_us.json`.  ember-intl will normalize the the locale name to `en-us` at build time.

Also, I went ahead and versioned it as 2.21.0 so feel free to report back anything you find.

https://github.com/jasonmit/ember-intl/releases/tag/2.21.0

**Comment by travisghansen** [comment]
@jasonmit Thanks!  I'll have my team review to see how that works both from a dev and prod perspective and then provide feedback either way.

**Comment by travisghansen** [comment]
@jasonmit so far this looks like it will fit out need perfectly.  I would only suggest (not needed for my use case) that someone may want to supply an absolute path vs relative.  Also (forgive my ignorance), if I understand correctly if I'm going the `npm` route the dependency only needs to be a `devDependencies` as the translations are compiled into the build and not read at run time?

**Comment by jasonmit** [comment]
Correct on the dev dep (unless we are talking about an addon then the translation package would be a regular dep within the addon).

As for absolute paths, I believe it's possible.  I'll investigate

**Comment by travisghansen** [comment]
@jasonmit ok, thanks again for the consideration!  This was tremendously helpful!

**Comment by estshy** [comment]
@jasonmit It looks nice. Works almost exactly as I was expecting. The only thing which I dislike is repeating translation path in each translation file.

Structure:
```
app
-- pods
---- notifications
------list
--------en-US.yaml
```

File en-us.yaml:
```
notifications:
   list:
     title: 'Notifications'
```
