### ISSUE TITLE
getLocalesByTranslations not documented

### ISSUE THREAD

**Issue by patric-eberle** [jasonmit/ember-intl#411]
By luck, I stumbled over the getLocalesByTranslations method, when searching for a solution to get the available translations. Can you please add that to your service documentation?

**Comment by vvohra** [comment]
I was going to document it but I realized that `getLocalesByTranslations` does not include locales that were sideloaded. Is that intentional?

**Comment by jasonmit** [comment]
Yes this is known and one of the reasons I didn't mark it officially public. I do plan to update the API to clean up how translations are resolved and in turn will fix this.

High on my list of things to do since it should simplify testing by removing the instance initializer.

**Comment by jasonmit** [comment]
@vvohra PR opened to add a public API for this and addressed the issue you're seeing.

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-intl/releases/tag/2.17.0 closes this out
