### ISSUE TITLE
Integration test helper does not wait for translations to be loaded

### ISSUE THREAD

**Issue by eshtadc** [jasonmit/ember-intl#412]
Hi there - I am getting warnings in my console that a translation for a specific locale is unavailable in my integration tests.  I am using the instance initializer and setting a locale as indicated in the documentation about integration tests.  I only see this issue when I am using the service directly (in my case within another service) rather than using the helpers within hbs files.  I've tracked this down to the instance initializer.  When looping through and adding translations, it does not have any way to wait for the translation to be loaded.  The addTranslations function itself returns a promise but it is not passed through the instance initializer so there is now way to wait for it to complete before continuing with the test.

### Environment
- Ember Version: 2.10.0
- Ember CLI Version: 2.10.0
- Ember Intl Version: 2.16.1
- Browser(s): Chrome (latest)
- Node Version: 5.6.0

**Comment by Turbo87** [comment]
@eshtadc can you share a minimal project that reproduces this issue?

**Comment by jasonmit** [comment]
@eshtadc updated the documentation and added a test to verify the wait test helper works.

https://guides.emberjs.com/v2.7.0/testing/testing-components/#toc_waiting-on-asynchronous-behavior
https://github.com/jasonmit/ember-intl/pull/413

**Comment by eshtadc** [comment]
Wow - you are fast.  I just came back this in the evening to add some more details to the report and saw your example updated with `wait`.  Works great!  Thanks for the helpful response as well as the doc updates for the next person.
