### ISSUE TITLE
Is it possible to use promise as value?

### ISSUE THREAD

**Issue by nightire** [jasonmit/ember-intl#414]
We're trying to build an i18n system on top of ember-intl with a backend service to provide create entries on the fly, here are what we've been done currently:

1. extend `ember-intl/services/intl` to overwrite its adapter property, delegate to a custom adapter when our service is enabled
2. extend `ember-intl/adapters/default` to overwrite `findTranslationByKey`, fire a request to our backend service to create a new entry

The problem is: since a promise get returned, we don't know how to resolve it as a valid value to let ember-intl process it.

I have wrap this promise into a PromiseProxy to provide a `type` so I can trace it deeper until I hit `intl-messageformat/compiler.js`, seems it requires an AST structure to continue its work, I don't know how to transform a promise to a valid AST, so I'm here to ask helps or suggestions, how should we deal a promise value with ember-intl?

**Comment by jasonmit** [comment]
I am not entirely sure what you mean by: "we don't know how to resolve it as a valid value to let ember-intl process it."

I don't image the `intlService.t` or `intlService.formatMessage` API is the thing giving you problem, it's likely the `t/formatMessage/formatHtmlMessage` helper(s) - correct?

If so, this so do-able you would likely need to refactor the helper as [`getValue`](https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/addon/helpers/-format-base.js#L33) is now a promise.

I would implement a compute method on the helpers you want to be async, I wouldn't touch the base helper.

```js
// app/helpers/t.js
// This is all untested, just wrote it on the fly to give you a rough idea how you could
// make the t-helper promise-aware.
import Helper from 'ember-intl/helpers/t';
import { LiteralWrapper } from 'ember-intl/helpers/l';

export default Helper.extend({
  translation: null,
  compute(params, hash) {
    if (this.translation) { return this.translation; }

    this.getValue(params, hash).then((translatedResponse) => {
       /* calls the original compute function but instructs
        * ember-intl to not to look up the translation */
      this.translation = this._super([new LiteralWrapper(translatedResponse)], hash);
      this.recompute();
    });
  }
});
```

I think you could use `ember-promise-helper` as an example of how you might implement helper whos value is a promise. https://github.com/fivetanley/ember-promise-helpers/blob/master/addon/helpers/await.js

**Comment by jasonmit** [comment]
Closing since this isn't an issue, feel free to ask questions in this thread or via Slack.  I'd be happy to help.

**Comment by nightire** [comment]
@jasonmit Hi, thank you, I'm trying your suggestions right now, hope will give some feedback soon.

BTW, slack doesn't have a dedicate channel for ember-intl, where is the right place to chat?

**Comment by jasonmit** [comment]
@nightire topic-i18n is the generic internalization channel.  Feel free to ping me there
