### ISSUE TITLE
PROPOSAL: inline default translations

### ISSUE THREAD

**Issue by jasonmit** [jasonmit/ember-intl#421]
Translations are usually single-use.  So it makes sense to keep your app's default locale as close as possible to the template.  By being able to glance at your template and see the translations that will be rendered provides valuable context to the developer/designer.

The syntax may look something like:

```hbs
{{#t key="app.store.coupon" couponCode=model.code savings=model.savingsPrice}}
  {couponCode} to save {savings, currency, USD} on your next purchase!
{{/t}}
```

This would involve at build time stripping out the inner text of the `t` helper into a hash with the key being `app.store.coupon` and value being `{couponCode} to save {savings, currency, USD} on your next purchase!`.  The build process will walk the templates across your addon/app and either bundle or write the default locale's translation to the `dist/` (same behavior that exists today).

What is left after the preprocessing is what you would write today:

```hbs
{{t key="app.store.coupon" couponCode=model.code savings=model.savingsPrice}}
```

```js
// dist/translations/<default locale>.json (or bundled into the app at build time)
{
  "app.store.coupon": "{couponCode} to save {savings, currency, USD} on your next purchase!"
}
```
The above syntax will be entirely optional, so compatibility should not be a concern.

/cc @Turbo87 since you wrote a nice IDE tool to expand translation keys to text, I'd like your opinion.  I feel this will tackle the issue w/o tooling for those majority of times where your translations are single use.

**Comment by jasonmit** [comment]
The more I thought about it, the more I think it will just lead to confusion.  Reason being, people might assume you can add htmlbars within the translation string and things would just work... which isn't the case.

**Comment by Turbo87** [comment]
yeah, I tend to agree. I thought about whether we could actually make that work, but haven't found a good way to do it yet.
