### ISSUE TITLE
Addon unit test fails with "Cannot read property 'modulePrefix' of undefined"

### ISSUE THREAD

**Issue by pauc** [jasonmit/ember-intl#427]
I am using ember-intl in an addon and I found I can not make a service test to work.

On the `setup()` call of the test, when trying to get the intl service, the tests fails with the message `Promise rejected before "it exists": Cannot read property 'modulePrefix' of undefined`. Using the debugger you can see that the error is caused by this line: https://github.com/jasonmit/ember-intl/blob/29de2f81dfbf130d5052c48b77f9d5cd4a1a8f5e/packages/ember-intl/addon/services/intl.js#L117

Any ideas about how to fix this?

### Environment

- Ember Version: 2.11.0
- Ember CLI Version: 2.11.0
- Ember Intl Version: 2.19.0
- Browser(s): Chromium, PhantomJS
- Node Version: 6.9.4

### Steps to Reproduce

In a blank addon run `ember install ember-intl` and add a service with a test: 

`addon/services/foo.js`:
```js
import Ember from 'ember';

export default Ember.Service.extend({
});
```

`app/services/foo.js`:
```js
export { default } from 'addon-name/services/foo';
```

`tests/unit/services/foo-test.js`:
```js
import { moduleFor, test } from 'ember-qunit';
import Ember from 'ember';

moduleFor('service:foo', 'Unit | Service | foo', {
  // Specify the other units that are required for this test.
  needs: ['service:intl'],

  setup() {
    const intl = Ember.getOwner(this).lookup('service:intl');
    intl.setLocale('en-us');
  }
});

// Replace this with your real tests.
test('it exists', function(assert) {
  let service = this.subject();
  assert.ok(service);
});
```

Thank you for all this amazing work!!

**Comment by pauc** [comment]
Solved adding a couple of explicit dependencies to the test:

```
import { moduleFor, test } from 'ember-qunit';
import Ember from 'ember';

moduleFor('service:foo', 'Unit | Service | foo', {
  // Specify the other units that are required for this test.
  needs: [
    'config:environment',
    'service:intl',
    'ember-intl@adapter:default'
  ],

  setup() {
    const intl = Ember.getOwner(this).lookup('service:intl');
    intl.setLocale('en-us');
  }
});

// Replace this with your real tests.
test('it exists', function(assert) {
  let service = this.subject();
  assert.ok(service);
});
```

**Comment by chadian** [comment]
@jrock2004 I received the same error which was fixed by adding:
```
    'cldr:en',
```
If you have more than one language `en`, `fr`, `de`, etc... include it as well in your `needs` list.
