### ISSUE TITLE
Possible small changes for app on Ember 2.11 with ember-intl 2.20.1

### ISSUE THREAD

**Issue by jrburke** [jasonmit/ember-intl#430]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version (actually v2.20.1, which is newer than the 2.20.0 listed at that latest link)
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.11.0
- Ember CLI Version: 2.11.0
- Ember Intl Version: 2.20.1
- Browser(s): Chrome 55.0.2883.95 (64-bit)
- Node Version: 6.9.4

### Steps to Reproduce

I am upgrading a project that was using ember-intl ^2.15.1 and Ember 2.8.3 to  ember-intl ^2.20.1 and Ember 2.11, and I hit a few snags. Below is the set of things I changed in ember-intl to get the app's tests to pass again.

If you think these are valid changes and do not have the bandwidth to do the changes, then I can look at setting up a PR for them. It may take a little bit of time to clear my work's open source policy.

[addons/adapters/default.js, lookup() method](https://github.com/jasonmit/ember-intl/blob/d83b4ab3fa95544173403bbe3e0a7d59ae45100a/packages/ember-intl/addon/adapters/default.js#L58)

Early return if no localeNames:

```javascript
  lookup(localeNames, translationKey) {
    if (!localeNames) {
        return;
    }
```

I think this should be done since in [addon/services/intl.js's lookup method](https://github.com/jasonmit/ember-intl/blob/d83b4ab3fa95544173403bbe3e0a7d59ae45100a/packages/ember-intl/addon/services/intl.js#L158) calls [_localeWithDefault](https://github.com/jasonmit/ember-intl/blob/d83b4ab3fa95544173403bbe3e0a7d59ae45100a/packages/ember-intl/addon/services/intl.js#L144) which can just return a string/null instead of an array if the `get(this, '_locale')` path is taken. This string/null value is then passed to the adapter's lookup.

Alternate fix could be to normalize returning an array always from the service's _localeWithDefault, and an empty array if no locale values.

[addon/services/intl.js, _hydrate() method](https://github.com/jasonmit/ember-intl/blob/d83b4ab3fa95544173403bbe3e0a7d59ae45100a/packages/ember-intl/addon/services/intl.js#L115)

* Check for `this.owner` then try the resolveRegistration, and if no config returned, early return.

```javascript
    const config = this.owner && this.owner.resolveRegistration('config:environment');
    if (!config) {
        return;
    }
```

This could be because some of our tests use the intl service in cases where there is not a whole application yet. I am not 100% sure on that though, I am still learning how that part of the app and tests are set up. But the tests worked in ember-intl 2.15.1. We could have also been doing something wrong this whole time though too.

**Comment by jasonmit** [comment]
I see no reason why we shouldn't exit in the case of the lookup.

As for the config missing I'm afraid we may mask other issues that may lead to people wondering why locale data was not loaded.

Add the following inside your fail test(s) and let me know if that fixes it.

```js
this.register('config:environment', {
  modulePrefix: 'app'
});
```

**Comment by jrburke** [comment]
I have a better understanding of the intl setup in this particular app, and there were a few issues that led me to post above, but I think they were errors on the app's part:

* Some setup code was trying trying to instantiate the intl service to grab the `t` method to hold onto for later. I changed it to just using `IntlClass.proto().t`, to get the `t` value from the prototype. That fixed the issue around a missing `this.owner`.
* The application-loading route template was using `{{t}}` in it before our async setup of setLocale was completed. Since the application-loading template ran before waiting for the application's `beforeModel`'s async work to set the locale, that led to the `lookup(localeNames...` call with a null `localeNames`. I removed the use of `{{t}}` in that template since it does not makes sense to try for a localization at that point anyway.

With those app changes, all the tests passed except for the unit test for the loc service that does some async setup of the `ember-intl` service. For that one I added the register you suggested:

```javascript
this.register('config:environment', {
  modulePrefix: 'app'
});
```

and then the test passed. So I am going to close this. I am surprised that the `this.register` call is needed though, but I still have much to learn on Ember so maybe I would have known better if I knew more.

Thanks for the guidance and for the great addon!

**Comment by jasonmit** [comment]
>  I am surprised that the this.register call is needed though, but I still have much to learn on Ember so maybe I would have known better if I knew more.

Unit tests require you to explicitly list out all dependencies via `needs` or to manually register them via `this.register`.  You likely could have added `needs: ['config:environment']` to the test that was failing versus having to register an empty config option.  That's something you'll need to decide on as I'm unsure what your tests are testing :)

Docs on the `needs` API:
https://guides.emberjs.com/v2.11.0/testing/testing-controllers/#toc_testing-controller-needs

> Thanks for the guidance and for the great addon!
❤️
