### ISSUE TITLE
Using within an addon

### ISSUE THREAD

**Issue by lmcardle** [jasonmit/ember-intl#432]
Is there anything special that needs to be done to get this addon working within addons? running `ember install ember-intl` runs the blueprint, which adds a sample translations/en-us.yaml file. Next I set the locales and baseLocale properties and then added a simple lookup in the template. However when 'lookup' gets called, it gets called with null as the localName, which causes `this._localeWithDefault(localeName);` to fail.

Here is a simple repo showing the issue: https://github.com/lmcardle/sample-addon-with-ember-intl.

Note, if I set the locale programmatically, with the below code, it works. However I am trying to set the locale at build time:
```
intl: Ember.inject.service(),
beforeModel() {
  return this.get('intl').setLocale('en-us');
}
```

**Comment by jasonmit** [comment]
Thanks for reporting, I'll investigate today.

**Comment by jasonmit** [comment]
> Note, if I set the locale programmatically, with the below code, it works. However I am trying to set the locale at build time.

Okay so I should have noticed this immediately but didn't, this isn't the intended use of `baseLocale`. Base locale is currently only used to detect missing keys at build time.

In 3.0, you'll have access to the `intl.baseLocale` from `config/environment`.  I plan to release that in the next few days.

```js
import config from './config/environment';

export default Ember.Route.extend({
  beforeModel() {
    /* contrived example of checking the session for a locale and falling back to the baseLocale */
    return this.get('intl').setLocale(this.session.locale || config.intl.baseLocale);
  }
});
```

https://github.com/jasonmit/ember-intl/blob/5f72b5279a22dbf7b43db4670bbc98ba2821f4b2/packages/ember-intl/index.js#L200-L202

**Comment by jasonmit** [comment]
Actually, I'll reopen and will investigate how feasible it is to backport this functionality to 2.x along with defaulting the service's locale to the baseLocale when setLocale is never called.

**Comment by jasonmit** [comment]
Updated my previous comment, closing as baseLocale is being removed in 3.0 to simplify the code base as it's own used to detect missing translations at build time against the primary/base locale.  That feature goes away in 3.0.
