### ISSUE TITLE
Repo field incorrect in package.json

### ISSUE THREAD

**Issue by mjuniper** [jasonmit/ember-intl#433]
- [X] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

I may be mistaken, but I believe the repository field in package.json is incorrect. It's unclear to me what it should be though. The reason I noticed this is because [ember observer](https://emberobserver.com/addons/ember-intl) can't get the repo info which is hurting ember-intl's score. Maybe the problem is actually on ember observer's side (it doesn't understand a monorepo).

**Comment by jasonmit** [comment]
Yeah I noticed this a few weeks ago, I believe this is on Ember Observer's end.  I'll try and to reach out to the maintainers to see if there is anything I can do to resolve it.

**Comment by jasonmit** [comment]
Spoke with Katie, she said Ember Observer doesn't support monorepo (and likely never will.)
> it makes sense in a way, because otherwise all those addons would get credit for the stars, contributors to the monorepo

I'll need to investigate undoing the monorepo or just accept that ember-intl will always be scored at 8/10.

**Comment by jasonmit** [comment]
Mono repository has been removed, in the process of kicking off a correction for the ember observer.

**Comment by jasonmit** [comment]
Correction to Ember Observer submitted, so I'm going to go ahead and close this.

**Comment by jasonmit** [comment]
Just to report back, looks like now Ember Observer has re-scored ember-intl.  Back to 10/10!

**Comment by mjuniper** [comment]
Awesome!
