### ISSUE TITLE
Converting Translations File Names to Lower Case

### ISSUE THREAD

**Issue by kkincade** [jasonmit/ember-intl#591]
The _ember-intl/index.js_ file (line 196) is converting translation file names lower case. So if I name my translation file _en-US.json_, it is output as _en-us.json_. You are likely doing this to ensure unique file names, but I'm wondering if the outcome is intentional or overlooked.

To me, it seems safer to keep the original casing. I ran into a Broccoli Merge error when I had _<app>public/translations/en-US.json_ that was trying to be merged with the _<app>/translations/en-us.json_ output from TranslationReducer.

### Environment

- Ember Version: 3.1.4
- Ember CLI Version: 3.1.4
- Ember Intl Version: 3.0.0
- Browser(s): All
- Node Version: 8.11.3

**Comment by jasonmit** [comment]
It's intentionally normalizing the locale names.

> I ran into a Broccoli Merge error when I had public/translations/en-US.json that was trying to be merged with the /translations/en-us.json output from TranslationReducer.

Can you explain this part further, I'm unsure I understand what's going on.

**Comment by kkincade** [comment]
Previously we were placing our translations in _<app>/public/translations_ instead of using the **publicOnly: true** method. After switching to the **publicOnly: true** method, I had forgotten to remove the old translation files from the _public_ folder. Broccoli was attempting to merge _<app>/public/translations/en-US.json_ with the _en-us.json_ output from the TranslationReducer. It saw there was a capitalization conflict and the build would fail as a result.

This was a good thing because it led me to find the duplicate translations, but it made me wonder why the capitalization of the file names was happening. We serve the files from our own backend server, so I had to go back and check to make sure the capitalization change wouldn't cause any issues with our server side code.

**Comment by jasonmit** [comment]
Ah, likely a case of the addon's public tree output was failing overwriting the app's public tree (your original files written to assets).  I think ember-intl did the right thing in failing, which led to you discovering the file conflict.

Do you feel there is a bug here and if so how would you propose it be addressed?
