### ISSUE TITLE
The disablePolyfill option is broken

### ISSUE THREAD

**Issue by kanongil** [jasonmit/ember-intl#686]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember CLI Version: **3.5.0**
- Ember Intl Version: **3.5.0**

### Steps to Reproduce

1. set `disablePolyfill: true` in `config/environment.js`
1. build it
1. observe that is put into `dist/assets/intl/` regardless.

**Comment by buschtoens** [comment]
> 1. set `disablePolyfill: true` in `config/environment.js`

Try `config/ember-intl.js` instead. 😉
